load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "config_proto",
    srcs = ["config.proto"],
)

cc_proto_library(
    name = "config_cc_proto",
    deps = [":config_proto"],
)

proto_library(
    name = "symbol_registry_proto",
    srcs = ["symbol_registry.proto"],
)

cc_proto_library(
    name = "symbol_registry_cc_proto",
    deps = [":symbol_registry_proto"],
)


cc_library(
    name = "config",
    srcs = ["config.cc"],
    hdrs = ["config.h"],
    copts = ["-std=c++20"],
    deps = [
        ":config_cc_proto",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@protobuf",
    ],
)

cc_test(
    name = "config_test",
    srcs = ["config_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":config",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "symbol_registry",
    srcs = ["symbol_registry.cc"],
    hdrs = ["symbol_registry.h"],
    copts = ["-std=c++20"],
    deps = [
        ":symbol_registry_cc_proto",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@protobuf",
    ],
)

cc_test(
    name = "symbol_registry_test",
    srcs = ["symbol_registry_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":symbol_registry",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "slicer",
    srcs = ["slicer.cc"],
    hdrs = ["slicer.h"],
    copts = ["-std=c++20"],
    deps = [
        ":config_cc_proto",
        "//core:rom",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/types:span",
    ],
)

cc_test(
    name = "slicer_test",
    srcs = ["slicer_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":config",
        ":slicer",
        "//core:rom",
        "@abseil-cpp//absl/types:span",
        "@googletest//:gtest_main",
    ],
)


