load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")
load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "config_proto",
    srcs = ["config.proto"],
)

cc_proto_library(
    name = "config_cc_proto",
    deps = [":config_proto"],
)

proto_library(
    name = "symbol_registry_proto",
    srcs = ["symbol_registry.proto"],
)

cc_proto_library(
    name = "symbol_registry_cc_proto",
    deps = [":symbol_registry_proto"],
)


cc_library(
    name = "config",
    srcs = ["config.cc"],
    hdrs = ["config.h"],
    copts = ["-std=c++20"],
    deps = [
        ":config_cc_proto",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@protobuf",
    ],
)

cc_test(
    name = "config_test",
    srcs = ["config_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":config",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "symbol_registry",
    srcs = ["symbol_registry.cc"],
    hdrs = ["symbol_registry.h"],
    copts = ["-std=c++20"],
    deps = [
        ":symbol_registry_cc_proto",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@protobuf",
    ],
)

cc_test(
    name = "symbol_registry_test",
    srcs = ["symbol_registry_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":symbol_registry",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "slicer",
    srcs = ["slicer.cc"],
    hdrs = ["slicer.h"],
    copts = ["-std=c++20"],
    deps = [
        ":config_cc_proto",
        "//core:rom",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/types:span",
    ],
)

cc_test(
    name = "slicer_test",
    srcs = ["slicer_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":config",
        ":slicer",
        "//core:rom",
        "@abseil-cpp//absl/types:span",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "disassembler",
    srcs = ["disassembler.cc"],
    hdrs = ["disassembler.h"],
    copts = ["-std=c++20"],
    deps = [
        ":symbol_registry",
        "//core:mips",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/types:span",
    ],
)

cc_test(
    name = "disassembler_test",
    srcs = ["disassembler_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":disassembler",
        ":symbol_registry",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/types:span",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "relocations",
    srcs = ["relocations.cc"],
    hdrs = ["relocations.h"],
    copts = ["-std=c++20"],
    deps = [
        ":symbol_registry",
        "//core:mips",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/types:span",
    ],
)

cc_test(
    name = "relocations_test",
    srcs = ["relocations_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":relocations",
        ":symbol_registry",
        "//core:mips",
        "@abseil-cpp//absl/types:span",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "jump_tables",
    srcs = ["jump_tables.cc"],
    hdrs = ["jump_tables.h"],
    copts = ["-std=c++20"],
    deps = [
        ":symbol_registry",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/types:span",
    ],
)

cc_test(
    name = "jump_tables_test",
    srcs = ["jump_tables_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":jump_tables",
        ":symbol_registry",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "linker_script",
    srcs = ["linker_script.cc"],
    hdrs = ["linker_script.h"],
    copts = ["-std=c++20"],
    deps = [
        ":config_cc_proto",
        ":symbol_registry",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
    ],
)

cc_test(
    name = "linker_script_test",
    srcs = ["linker_script_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":config",
        ":linker_script",
        ":symbol_registry",
        "@abseil-cpp//absl/strings",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "roundtrip_test",
    srcs = ["roundtrip_test.cc"],
    copts = ["-std=c++20"],
    data = [
        "testdata/custom_sample.c",
        "//toolchain:all_files",
    ],
    deps = [
        ":disassembler",
        ":jump_tables",
        ":relocations",
        ":symbol_registry",
        "@abseil-cpp//absl/strings:str_format",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "auto_symbols",
    srcs = ["auto_symbols.cc"],
    hdrs = ["auto_symbols.h"],
    copts = ["-std=c++20"],
    deps = [
        ":relocations",
        ":symbol_registry",
        ":symbol_registry_cc_proto",
        "//core:mips",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/types:span",
    ],
)

cc_test(
    name = "auto_symbols_test",
    srcs = ["auto_symbols_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":auto_symbols",
        ":symbol_registry",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "splitter_lib",
    srcs = ["splitter.cc"],
    hdrs = ["splitter.h"],
    copts = ["-std=c++20"],
    deps = [
        ":auto_symbols",
        ":config",
        ":config_cc_proto",
        ":disassembler",
        ":linker_script",
        ":slicer",
        ":symbol_registry",
        "//core:rom",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
    ],
)

cc_test(
    name = "splitter_test",
    srcs = ["splitter_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":splitter_lib",
        "//core:rom",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings:str_format",
        "@googletest//:gtest_main",
    ],
)

cc_binary(
    name = "splitter",
    srcs = ["main.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":splitter_lib",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        "@abseil-cpp//absl/flags:usage",
        "@abseil-cpp//absl/strings:str_format",
    ],
)
