load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])

# Runnable targets for splitting each game via Bazel py_binary
py_binary(
    name = "split_harvest_moon_64",
    srcs = ["//tools:split.py"],
    args = ["harvest-moon-64"],
    data = [
        "//splat:harvest-moon-64",
        "//symbols:harvest-moon-64",
    ],
    deps = [
        "@pip//pyyaml",
    ],
    main = "//tools:split.py",
)

py_binary(
    name = "split_ogre_battle_64",
    srcs = ["//tools:split.py"],
    args = ["ogre-battle-64"],
    data = [
        "//splat:ogre-battle-64",
        "//symbols:ogre-battle-64",
    ],
    deps = [
        "@pip//pyyaml",
    ],
    main = "//tools:split.py",
)
