load("//rules:defs.bzl", "n64_game")

package(default_visibility = ["//visibility:public"])

n64_game(
    name = "harvest_moon_64",
    game = "harvest-moon-64",
    config = "//splat:harvest-moon-64",
    symbols = "//symbols:harvest-moon-64",
    rom = "//roms:harvest-moon-64.z64",
    srcs = [
        "//src/c/harvest-moon-64:srcs",
        "//src/cc/harvest-moon-64:srcs",
    ],
)

n64_game(
    name = "ogre_battle_64",
    game = "ogre-battle-64",
    config = "//splat:ogre-battle-64",
    symbols = "//symbols:ogre-battle-64",
    rom = "//roms:ogre-battle-64.z64",
    srcs = [
        "//src/ogre-battle-64:srcs",
    ],
)

# Convenient alias to format all C/C++ files across the codebase
alias(
    name = "format",
    actual = "//tools:format",
)

# Convenient alias to verify/tidy all C/C++ files across the codebase
alias(
    name = "tidy",
    actual = "//tools:tidy",
)

# Convenient alias to check decompilation progress
alias(
    name = "progress",
    actual = "//tools:progress",
)

# Convenient alias to interactively diff a function
alias(
    name = "diff",
    actual = "//tools:diff",
)

# Convenient alias to decompile a function with on-the-fly context
alias(
    name = "m2c",
    actual = "//tools:m2c",
)




