load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "mips_emulator",
    srcs = ["mips_emulator.cc"],
    hdrs = ["mips_emulator.h"],
    deps = [
        "//core:mips",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/types:span",
    ],
)

cc_test(
    name = "mips_emulator_test",
    srcs = ["mips_emulator_test.cc"],
    deps = [
        ":mips_emulator",
        "//core:mips",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "differential_fuzzer",
    srcs = ["differential_fuzzer.cc"],
    hdrs = ["differential_fuzzer.h"],
    deps = [
        ":mips_emulator",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
    ],
)

cc_test(
    name = "differential_fuzzer_test",
    srcs = ["differential_fuzzer_test.cc"],
    deps = [
        ":differential_fuzzer",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

