load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "endian",
    hdrs = ["endian.h"],
    copts = ["-std=c++20"],
    deps = [
        "@abseil-cpp//absl/types:span",
    ],
)

cc_test(
    name = "endian_test",
    srcs = ["endian_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":endian",
        "@abseil-cpp//absl/types:span",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "mips",
    srcs = ["mips.cc"],
    hdrs = ["mips.h"],
    copts = ["-std=c++20"],
    deps = [
        ":endian",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/types:span",
    ],
)

cc_test(
    name = "mips_test",
    srcs = ["mips_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":mips",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "sha1",
    srcs = ["sha1.cc"],
    hdrs = ["sha1.h"],
    copts = ["-std=c++20"],
    deps = [
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/types:span",
    ],
)

cc_test(
    name = "sha1_test",
    srcs = ["sha1_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":sha1",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "rom",
    srcs = ["rom.cc"],
    hdrs = ["rom.h"],
    copts = ["-std=c++20"],
    deps = [
        ":endian",
        ":sha1",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/types:span",
    ],
)

cc_test(
    name = "rom_test",
    srcs = ["rom_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":rom",
        ":sha1",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "process",
    srcs = ["process.cc"],
    hdrs = ["process.h"],
    copts = ["-std=c++20"],
    deps = [
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/time",
    ],
)

cc_test(
    name = "process_test",
    srcs = ["process_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":process",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/time",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "toolchain",
    srcs = ["toolchain.cc"],
    hdrs = ["toolchain.h"],
    copts = ["-std=c++20"],
    deps = [
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
    ],
)

cc_test(
    name = "toolchain_test",
    srcs = ["toolchain_test.cc"],
    copts = ["-std=c++20"],
    data = [
        "//toolchain:all_files",
    ],
    deps = [
        ":toolchain",
        "@abseil-cpp//absl/strings",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "compiler",
    srcs = ["compiler.cc"],
    hdrs = ["compiler.h"],
    copts = ["-std=c++20"],
    deps = [
        ":process",
        ":toolchain",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/time",
    ],
)

cc_test(
    name = "compiler_test",
    srcs = ["compiler_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":compiler",
        ":process",
        ":toolchain",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
        "@googletest//:gtest_main",
    ],
)

