load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "mips",
    srcs = ["mips.cc"],
    hdrs = ["mips.h"],
    copts = ["-std=c++20"],
    deps = [
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/types:span",
    ],
)

cc_test(
    name = "mips_test",
    srcs = ["mips_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":mips",
        "@googletest//:gtest_main",
    ],
)
