load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "source_resolver",
    srcs = ["source_resolver.cc"],
    hdrs = ["source_resolver.h"],
    copts = ["-std=c++20"],
    deps = [
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
    ],
)

cc_test(
    name = "source_resolver_test",
    srcs = ["source_resolver_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":source_resolver",
        "@abseil-cpp//absl/status",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "linker_script_adapter",
    srcs = ["linker_script_adapter.cc"],
    hdrs = ["linker_script_adapter.h"],
    copts = ["-std=c++20"],
    deps = [
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
    ],
)

cc_test(
    name = "linker_script_adapter_test",
    srcs = ["linker_script_adapter_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":linker_script_adapter",
        "@abseil-cpp//absl/status",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "rom_builder",
    srcs = ["rom_builder.cc"],
    hdrs = ["rom_builder.h"],
    copts = ["-std=c++20"],
    deps = [
        ":linker_script_adapter",
        ":source_resolver",
        "//core:compiler",
        "//core:sha1",
        "//core:toolchain",
        "//splitter:config",
        "//splitter:config_cc_proto",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
    ],
)

cc_test(
    name = "rom_builder_test",
    srcs = ["rom_builder_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":rom_builder",
        "//core:compiler",
        "//core:process",
        "//core:sha1",
        "//core:toolchain",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
        "@googletest//:gtest_main",
    ],
)

cc_binary(
    name = "builder",
    srcs = ["main.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":rom_builder",
        "//core:toolchain",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        "@abseil-cpp//absl/flags:usage",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
    ],
)
