load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = glob(["**"]),
)

cc_library(
    name = "common_hdrs",
    hdrs = glob(["*.h"]),
    includes = ["."],
)

cc_library(
    name = "boot",
    srcs = ["boot.c"],
    copts = ["-Dmain=BootMain"],
    deps = [
        ":common_hdrs",
        "//mocks/ultra64",
    ],
)
