load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])


py_binary(
    name = "install_toolchain",
    srcs = ["install_toolchain.py"],
    main = "install_toolchain.py",
)

py_binary(
    name = "format",
    srcs = ["format.py"],
    main = "format.py",
)

py_binary(
    name = "tidy",
    srcs = ["tidy.py"],
    main = "tidy.py",
)

py_binary(
    name = "progress",
    srcs = ["progress.py"],
    deps = [
        "@pip//pyyaml",
    ],
    main = "progress.py",
)




