load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])

exports_files([
    "create_bps.py",
    "split.py",
])

py_binary(
    name = "split",
    srcs = ["split.py"],
    data = [
        "//splat:configs",
        "//symbols:all_symbols",
    ],
    main = "split.py",
)

py_binary(
    name = "create_bps",
    srcs = ["create_bps.py"],
    main = "create_bps.py",
)
